networks:
  app-net:
    driver: bridge

volumes:
  redis:
  mongo:

services:
  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - app-net
    restart: unless-stopped

  mongo:
    image: mongodb/mongodb-community-server:8.0-ubi9-slim
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - app-net
    restart: unless-stopped
  #app: